spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/account_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: account
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/account_db
    password: postgres
    user: postgres
    schemas: account
    out-of-order: true
    locations:
      - classpath:db/migration